### ISSUE TITLE
xvi can segfault when it runs out of RAM

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#129]
All calls to alloc() should be checked and fail gracefully.

Repeat-by:
% sh
$ ulimit -v 2500
$ ./xvi
79aa[esc]yyppppppppppppppppppppppppppppppppppppppppppppppppp

The segfaults I have seen from this are always happening in throw() called from copy_lines(), e.g.:
```
#1  0x080495c1 in throw (lineptr=0x805d788) at alloc.c:409
#2  0x080598b6 in copy_lines (from=<optimized out>, to=to@entry=0x0)
    at yankput.c:800
#3  0x08059fe3 in do_put (win=0x97cd1a0, location=0x97cd200, direction=0, 
    name=64) at yankput.c:685
#4  0x08057cad in do_cmd (cmd=0x97cd210) at vi_cmds.c:70
#5  0x080516d6 in HandleCommand (cmd=0x97cd210) at normal.c:255
```
In throw(), its lineptr is a valid pointer but lineptr->l_text is not a valid pointer, nor NULL.

**Comment by martinwguy** [comment]
Fixed by f66b96f4
