### ISSUE TITLE
xvi can segfault when running out of RAM

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#130]
xvi segfaults when it runs out of RAM while inserting a line of text.

Repeat-by:
```
bash$ sh
$ ulimit -v 2500
$ src/xvi
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
... until it segfaults. gdb says:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x61616161) at malloc.c:2929
2929	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x61616161) at malloc.c:2929
#1  0x0805c7a6 in _replchars (window=0x845b1a0, line=0x845aff8, start=127, 
    nchars=0, newstring=0x806ddd8 <s> "a") at undo.c:351
#2  0x0805c5d9 in replchars (window=0x845b1a0, line=0x845aff8, start=127, 
    nchars=0, newstring=0x806ddd8 <s> "a") at undo.c:227
#3  0x0804cdcc in i_proc (c=97) at edit.c:423
#4  0x0804fad7 in xvi_handle_event (ev=0xbf825970) at events.c:165
#5  0x080622ab in tcap_scr_main (argc=1, argv=0xbf825a64) at tcap_scr.c:350
#6  0x08062061 in main (argc=1, argv=0xbf825a64) at tcapmain.c:31
```

**Comment by martinwguy** [comment]
Fixed by c8a8f4c5
