### ISSUE TITLE
xvi segfaults when running out of RAM and forcing a save.

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#131]
When xvi runs out of RAM (like in issue #130) you can't write the file.
To ":w foo" (it says "Cannot open preserve file /tmp/#foo.tmp"). If you then force the write ``:w! foo" it segfaults here:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x08049ef1 in exCommand (cmdline=0x806dc42 <inbuf+2> "", interactive=1)
    at cmdline.c:437
437			    arg = argv[0];	/* unnecessary but correct */
(gdb) bt
#0  0x08049ef1 in exCommand (cmdline=0x806dc42 <inbuf+2> "", interactive=1)
    at cmdline.c:437
#1  0x0804fd66 in c_proc (c=13) at events.c:280
#2  0x0804fad7 in xvi_handle_event (ev=0xbfa19f40) at events.c:165
#3  0x080622b5 in tcap_scr_main (argc=1, argv=0xbfa1a034) at tcap_scr.c:350
#4  0x0806206b in main (argc=1, argv=0xbfa1a034) at tcapmain.c:31
```

**Comment by martinwguy** [comment]
0bf4ac63 fixes the segfault.
